- name: パスワード更新
  win_user:
    name: "{{ login_id }}"
    password: "{{ login_password }}"
    state: present
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_scheme: http
    ansible_port: 5985
    ansible_winrm_server_cert_validation: ignore
