---
- name: Get works.
  uri:
    url: "http://admingate-core-server:8081/admin/works"
    headers:
      HTTP_REMOTEUSER: "{{ username }}"
      X-Auth-Role: ADMIN
    method: GET
    validate_certs: false
    return_content: yes
    status_code: 200
  register: admin_works

- name: Find existing work id.
  set_fact:
    work_id: "{{ item.id }}"
  when: item.name == name and work_id is not defined
  loop: "{{ admin_works.json | default([]) }}"
  loop_control:
    label: "{{ item.name }}"

- name: Ensure work exists.
  assert:
    that:
      - work_id is defined
    fail_msg: "Work not found: {{ name }}"

- name: Disable work.
  uri:
    url: "http://admingate-core-server:8081/admin/works/{{ work_id }}/status"
    headers:
      HTTP_REMOTEUSER: "{{ username }}"
      X-Auth-Role: ADMIN
      Content-Type: "application/json"
    method: POST
    body_format: json
    body:
      status: disabled
    validate_certs: false
    return_content: yes
    status_code: 200
