---
- name: Get works.
  uri:
    url: "http://admingate-core-server:8081/admin/works"
    headers:
      HTTP_REMOTEUSER: "{{ username }}"
      X-Auth-Role: ADMIN
    method: GET
    validate_certs: false
    return_content: yes
    status_code: 200
  register: admin_works

- name: Find existing work id.
  set_fact:
    work_id: "{{ item.id }}"
  when: item.id == id and work_id is not defined
  loop: "{{ admin_works.json | default([]) }}"
  loop_control:
    label: "{{ item.name }}"

- name: Build file transfer permissions.
  set_fact:
    work_file_transfer_permissions:
      http:
        connect: true
        read: "{{ not (disableDownload | default(false, true) | bool) }}"
        write: "{{ not (disableUpload | default(false, true) | bool) }}"
      web_sftp:
        connect: true
        read: "{{ not (disableDownload | default(false, true) | bool) }}"
        write: "{{ not (disableUpload | default(false, true) | bool) }}"
      ftp:
        connect: true
        read: "{{ not (disableDownload | default(false, true) | bool) }}"
        write: "{{ not (disableUpload | default(false, true) | bool) }}"
      sftp:
        connect: true
        read: "{{ not (disableDownload | default(false, true) | bool) }}"
        write: "{{ not (disableUpload | default(false, true) | bool) }}"
      tftp:
        connect: true
        read: "{{ not (disableDownload | default(false, true) | bool) }}"
        write: "{{ not (disableUpload | default(false, true) | bool) }}"

- name: Build work payload.
  set_fact:
    work_payload:
      id: "{{ id }}"
      name: "{{ name }}"
      worker_ids: "{{ resultUsers | default([], true) | unique | list }}"
      manager_ids: "{{ manageUsers | default([], true) | unique | list }}"
      target_ids: "{{ resultConnections | default([], true) | unique | list }}"
      file_transfer_permissions: "{{ work_file_transfer_permissions }}"

- name: Build work periods.
  set_fact:
    work_valid_periods: >-
      {{
        work_valid_periods | default([], true) + [
          (
            {
              'valid_from_date': item.validFrom,
              'valid_until_date': item.validUntil
            }
            | combine(
                {
                  'daily_start_time': '%02d:%02d' | format(
                    item.startHour | default('0') | int,
                    item.startMinute | default('0') | int
                  )
                }
                if (
                  item.specificTime | default(false, true) | bool
                  and (item.startHour | default('') | string | trim is match('^[0-9]+$'))
                  and (item.startMinute | default('') | string | trim is match('^[0-9]+$'))
                  and ((item.startHour | default('0') | int) >= 0 and (item.startHour | default('0') | int) <= 23)
                  and ((item.startMinute | default('0') | int) >= 0 and (item.startMinute | default('0') | int) <= 59)
                )
                else {}
              )
            | combine(
                {
                  'daily_end_time': '%02d:%02d' | format(
                    item.endHour | default('0') | int,
                    item.endMinute | default('0') | int
                  )
                }
                if (
                  item.specificTime | default(false, true) | bool
                  and (item.endHour | default('') | string | trim is match('^[0-9]+$'))
                  and (item.endMinute | default('') | string | trim is match('^[0-9]+$'))
                  and ((item.endHour | default('0') | int) >= 0 and (item.endHour | default('0') | int) <= 23)
                  and ((item.endMinute | default('0') | int) >= 0 and (item.endMinute | default('0') | int) <= 59)
                )
                else {}
              )
          )
        ]
      }}
  loop: "{{ Periods | default([], true) }}"
  loop_control:
    label: "{{ item.validFrom }} - {{ item.validUntil }}"

- name: Add work periods to work payload.
  set_fact:
    work_payload: >-
      {{
        work_payload | combine({
          'valid_periods': work_valid_periods | default([], true)
        })
      }}
  when: (Periods | default([], true) | length) > 0

- name: Create work.
  uri:
    url: "http://admingate-core-server:8081/admin/works"
    headers:
      HTTP_REMOTEUSER: "{{ username }}"
      X-Auth-Role: ADMIN
      Content-Type: "application/json"
    method: POST
    body_format: raw
    body: "{{ work_payload | to_json }}"
    validate_certs: false
    status_code: 201
  when: work_id is not defined

- name: Update work.
  uri:
    url: "http://admingate-core-server:8081/admin/works/{{ work_id }}"
    headers:
      HTTP_REMOTEUSER: "{{ username }}"
      X-Auth-Role: ADMIN
      Content-Type: "application/json"
    method: PUT
    body_format: raw
    body: "{{ work_payload | to_json }}"
    validate_certs: false
    status_code: 200
  when: work_id is defined
